### ISSUE TITLE
Support Drupal installations in sub-directories of the repo root

### ISSUE THREAD

**Issue by hawkeyetwolf** [kalamuna/drupal-vm#10]
Right now, we handle the UCSF (Acquia) repo specially, distinct from the other (Pantheon) sites. The former houses Drupal inside a `docroot` parent folder, whereas Pantheon's repo root _is_ the Drupal root.

The proposed structure would look like this:

```
sites:
  # Pantheon sites and other hosts with no parent directory
  root:
    - eecs
    - dent
    - greenbiz
    - another_pantheon_site
  # Acquia sites and other hosts using docroot (non-multisite only)
  docroot:
    - non_multisite_acquia_repo
    - another_acquia_site
  # Other host with non-standard Drupal root
  foo/bar:
    - client_x

multisites:
  # Multisite instances on Acquia and other hosts using docroot
  docroot:
    ucsf:
      - nursing
      - silvermandigitallibrary
```

With this breakdown, I can easily implement the programmatic site configs in Vagrantfile and Ansible tasks.
